### ISSUE TITLE
Relax dependency on Diff?

### ISSUE THREAD

**Issue by magthe** [simonmichael/shelltestrunner#1]
I've just built a version of `shelltestrunner` with Diff version 0.3.4. It seems to work beautifully, so I'd love to see a release of a version with a bound of `< 0.3.5`.

**Comment by simonmichael** [comment]
I'm sorry for missing this. I would welcome a pull request updating any dependency bounds.

**Comment by simonmichael** [comment]
Oh, I see this is already done. But we need a release.

**Comment by simonmichael** [comment]
Opened #5, closing this.
