### ISSUE TITLE
-h should be equivalent to --help

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/shelltestrunner#12]
Currently -h is equivalent to --hide-successes. It should be --help, but I'm having trouble fixing it due to https://github.com/ndmitchell/cmdargs/issues/22 . Help welcome.

**Comment by schoettl** [comment]
In current master, -h is an alias for --help. This is because --hide-success has the `&= explicit` property.

Doesn't this close this issue? (Even if the issue in cmdargs is still open.)

**Comment by simonmichael** [comment]
Yes seems fixed, thanks!
