### ISSUE TITLE
Keep or remove the secondary comment character `*`?

### ISSUE THREAD

**Issue by schoettl** [simonmichael/shelltestrunner#23]
I noticed the addition of `*` as a comment character in [the parser](https://github.com/simonmichael/shelltestrunner/blob/master/src/Parse.hs#L394):

This is only for hierachical org mode folding, right? I admit, it is convenient but there are other ways for code folding, e.g.
- having a mode/filetype for shelltest files that supports folding
- use Vim's built-in manual folding (or an Emacs equivalent)
- split up tests in more separate files

Problems, I see with the `*` syntax:
- Non-orgmode users won't understand the intention of that uncommon `*` syntax for comments.
- I had to change my program under test as well as all tests because my program produced lines starting with `*` in its output.

I think it might be better to have only a minimum of comment characters (i.e. I'd prefer only the shell comment `#`).

Opinions?

**Comment by simonmichael** [comment]
@schoettl I think that's a good idea, to remove `*` from `commentline`. I added it in 2018 and I don't seem to be using it anywhere, in fact I have several tests where the data contains lines like that (and they seem to work as expected).
