### ISSUE TITLE
Specify .expected as a file?

### ISSUE THREAD

**Issue by alensiljak** [simonmichael/shelltestrunner#31]
Is it possible to specify the expected result as a file? This may be more convenient, separating the data from test spec.
The expected output may be cluttering the test file unnecessarily.

**Comment by alensiljak** [comment]
Or, perhaps, some sort of redirect from a text file is possible?

**Comment by simonmichael** [comment]
Tests can be arbitrary shell commands, so I guess you could test a command like (correct bash syntax IIRC):

$ diff <(PROG ...) 1234.expected

**Comment by simonmichael** [comment]
(Confirmed, requires `shelltest --shell=bash` here.)

**Comment by simonmichael** [comment]
Closing for now.
