### ISSUE TITLE
needs a release

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/shelltestrunner#5]
The last release was 1.3.5 in 2015/03. The next will be 2.0, currently blocked on #4.

**Comment by jonaprieto** [comment]
@simonmichael, while you release the version 2.0, I will thank you if you release in Hackage the upstream version. 1.9?

**Comment by simonmichael** [comment]
@jonaprieto, what are you missing from master that needs a release ? I have forgotten what's in there.

**Comment by jonaprieto** [comment]
Please see this: https://github.com/asr/apia/pull/95

**Comment by simonmichael** [comment]
Ok, so showing the command that was run ? You can see that by using the --debug flag with 1.3.5, is that of any use ?

**Comment by simonmichael** [comment]
shelltestrunner has fallen out of stackage nightly, and a release would fix that.
https://github.com/fpco/stackage/issues/3048

**Comment by asr** [comment]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got an error trying to install `shelltestrunner` 1.3.5. 

The current version on the master branch (commit  1c376f9) compiles with GHC 8.4.1-alpha1, so could you make a release, please?

Blocking https://github.com/agda/agda/issues/2878.

**Comment by simonmichael** [comment]
TIme to get this unstuck. I will do so asap, it may take a few days.

**Comment by simonmichael** [comment]
1.9 released! \o/

**Comment by simonmichael** [comment]
@asr by the way, where does Agda use shelltestrunner ? I'm not finding it.

**Comment by asr** [comment]
@simonmichael, thanks for releasing!

Agda uses shelltestrunner in her test-suite which *isn't* included in the tarball:

```
$ git clone https://github.com/agda/agda.git
$ cd agda
$ make test-size-solver
```
