### ISSUE TITLE
shelltest always uses the shell sh

### ISSUE THREAD

**Issue by asr** [simonmichael/shelltestrunner#6]
I'm getting the following error:

```
$ echo $0
bash

$ shelltest --version
shelltest 1.3.5
```

```
$ cat test.test
diff <(ghc -V) <(ghc -V)
<<<
>>>
>>>2
>>>= 0
```

```
$ shelltest test.test 
:test.test: [Failed]

Expected stderr: 

Got stderr:      
/bin/sh: 1: Syntax error: "(" unexpected

Expected exit code: 
0
Got exit code:      
2
```

Note that I'm using `bash` but the error mentions `sh`. The error is due to the command 
```
diff <(ghc -V) <(ghc -V)
```
is accepted by `bash` but rejected by `sh`,  and `shelltest` is using `sh`.

**Comment by asr** [comment]
CC'ing @jonaprieto.

**Comment by simonmichael** [comment]
I see you're right. Unfortunately [process](http://hackage.haskell.org/package/process) hardcodes "/bin/sh" on POSIX (and "cmd" on Windows) so shelltestrunner doesn't support this at present.

**Comment by asr** [comment]
> Unfortunately [process](http://hackage.haskell.org/package/process) hardcodes "/bin/sh" on POSIX

You are right. I filed https://github.com/haskell/process/issues/84.

**Comment by simonmichael** [comment]
As I just commented there, we probably don't want test success depending on current user's shell preference. It would be ok to specify it with a command-line option or some notation in the test though.

**Comment by asr** [comment]
> It would be ok to specify it with a command-line option or some notation in the test though.

A command-line option would be nice.
