### ISSUE TITLE
command arguments wrongly de-escaped ?

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/shelltestrunner#9]
I think there's a bug here, found in https://github.com/simonmichael/hledger/issues/573:
```
# \n should be passed as-is to echo. 
# Fails on my mac or travis, but apparently succeeds on another machine..
echo 'a\nb'
>>>
a\nb
>>>2
>>>=0
```

**Comment by simonmichael** [comment]
Our `runInteractiveCommandInDir` makes a `CreateProcess` using either `shell` or (with the `--shell` option) `proc`:
```
      run = maybe (shell cmd) (\shcmd -> proc shcmd ["-c", cmd]) sh
```
`shell` uses the first case of System.Process's internal helper `commandToProcess`:
```
commandToProcess :: CmdSpec -> (FilePath, [String])
commandToProcess (ShellCommand string) = ("/bin/sh", ["-c", string])
commandToProcess (RawCommand cmd args) = (cmd, args)
```
which in effect changes our `echo 'a\nb'` to `echo a\nb`:
```
>>> readCreateProcess (shell "echo 'a\\nb'") "" >>= putStr
a
b
```

If we used `proc` to run the command directly, like this, it would work:
```
>>> readCreateProcess (proc "echo" ["'a\\nb'"]) "" >>= putStr
'a\nb'
```
Could that be done, reliably ? Perhaps using helpers like [`words'`](http://hackage.haskell.org/package/hledger-lib-1.19.1/docs/Hledger-Utils-String.html#v:words-39-) ? I tried a bit without success.

**Comment by obfusk** [comment]
It's not a bug in shelltestrunner (or System.Process); it's a difference between `echo` as a separate command, as a `bash` built-in, and as a `sh` (in my case `sh` is `dash`) built-in.

```bash
bash$ echo 'a\nb'
a\nb
bash$ /bin/echo 'a\nb'
a\nb
bash$ echo -e 'a\nb'
a
b
```

```bash
sh$ echo 'a\nb'
a
b
sh$ /bin/echo 'a\nb'
a\nb
```

**Comment by simonmichael** [comment]
Ohh, very good point. That'll help.

**Comment by obfusk** [comment]
From https://en.wikipedia.org/wiki/Echo_(command):

> Nowadays, several incompatible implementations of echo exist on different operating systems (often several on the same system), some of them expanding escape sequences by default, some of them not, some of them accepting options (the list of which varying with implementations), some of them not.

**Comment by simonmichael** [comment]
How should this work ? 

I think intuitively and based on the name we usually expect shelltestrunner to run "shell commands", giving the same results as if you typed them interactively in a terminal. And "shell" means /bin/sh on posix and cmd.exe on windows by default, or some other shell if specified with --shell, as documented.

So perhaps it's already behaving as it should ? That test works with /bin/echo, or with bash's echo, but not with sh's or zsh's echo. It can be made to pass by changing the command to `/bin/echo`:
```
$ cat tests/_9b.test
$ /bin/echo 'a\nb'
a\nb
$ shelltest tests/_9b.test 
:tests/_9.test: [OK]

         Test Cases  Total      
 Passed  1           1          
 Failed  0           0          
 Total   1           1          
```
or by changing the shell to bash:
```
$ shelltest tests/_9.test --shell bash
:tests/_9.test: [OK]

         Test Cases  Total      
 Passed  1           1          
 Failed  0           0          
 Total   1           1          
```

**Comment by obfusk** [comment]
> So perhaps it's already behaving as it should

It is :)

**Comment by simonmichael** [comment]
**FAD**, Functioning As Designed
